build: false

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python35-x64"

matrix:
  fast_finish: false

install:
  - cmd: set "PATH=%PYTHON%;%PATH%"
  - cmd: python -m venv virtualenv
  - cmd: virtualenv\Scripts\activate.bat
  - cmd: pip install tox codecov

test_script:
  - cmd: tox -e py -- -n 2 --color=yes

after_test:
  - cmd: codecov

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
